Correction de deux bugs non trouvés au préalable. Par contre, le code ne compile toujours pas à cause d'un problème: undefined reference to `__cxa_pure_virtual'